[package]
name = "run_service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread"] }
hyper = "0.14"
tower = "0.4"
uuid = "1"
tempfile = "3"
